-- =====================================================================
-- SUPABASE SCHEMA: JEJAK WAKTU
-- Jalankan skrip ini di: Supabase Dashboard -> SQL Editor -> New Query -> Run
-- =====================================================================

-- 1. EXTENSIONS
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- ---------------------------------------------------------------------
-- 2. TABEL: albums (Buku Album Foto)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.albums (
    id VARCHAR(100) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    subtitle VARCHAR(255) DEFAULT NULL,
    era VARCHAR(50) DEFAULT NULL,
    decade VARCHAR(20) DEFAULT '1970s',
    category VARCHAR(50) DEFAULT 'sejarah-kota',
    cover_image TEXT NOT NULL,
    cover_color VARCHAR(30) DEFAULT '#422a1d',
    accent_color VARCHAR(30) DEFAULT '#b38241',
    description TEXT,
    location VARCHAR(150) DEFAULT 'Indonesia',
    curator VARCHAR(150) DEFAULT 'Arsiparis Jejak Waktu',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 3. TABEL: photos (Foto Polaroid & Kenangan)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.photos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    album_id VARCHAR(100) NOT NULL REFERENCES public.albums(id) ON DELETE CASCADE,
    title VARCHAR(255) NOT NULL,
    artist_1 VARCHAR(255) DEFAULT NULL,
    artist_2 VARCHAR(255) DEFAULT NULL,
    year VARCHAR(10) DEFAULT NULL,
    date VARCHAR(100) DEFAULT NULL,
    location VARCHAR(150) DEFAULT NULL,
    medium VARCHAR(255) DEFAULT NULL,
    dimensions VARCHAR(150) DEFAULT NULL,
    copyright VARCHAR(255) DEFAULT NULL,
    caption TEXT,
    image_src TEXT NOT NULL,
    thumb_src TEXT,
    tilt VARCHAR(20) DEFAULT '-2deg',
    tape VARCHAR(20) DEFAULT 'top-right',
    note TEXT,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 4. TABEL: events (Jadwal Event & Pameran Seni)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    theme VARCHAR(255) DEFAULT NULL,
    status VARCHAR(20) DEFAULT 'upcoming',
    start_date DATE NOT NULL,
    end_date DATE DEFAULT NULL,
    start_time TIME DEFAULT NULL,
    end_time TIME DEFAULT NULL,
    ticket_price VARCHAR(100) DEFAULT 'Gratis',
    ticket_quota INT DEFAULT NULL,
    location_text TEXT DEFAULT NULL,
    location_map TEXT DEFAULT NULL,
    artists TEXT DEFAULT NULL,
    poster_image TEXT DEFAULT NULL,
    description TEXT DEFAULT NULL,
    organizer VARCHAR(150) DEFAULT 'Jejak Waktu',
    album_id VARCHAR(100) DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 5. TABEL: bookings (Pemesanan Tiket Event)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.bookings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id BIGINT NOT NULL REFERENCES public.events(id) ON DELETE CASCADE,
    user_id BIGINT NOT NULL,
    qty INT DEFAULT 1,
    total_price VARCHAR(100) DEFAULT NULL,
    status VARCHAR(20) DEFAULT 'confirmed',
    booking_code VARCHAR(50) DEFAULT NULL,
    notes TEXT DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 6. TABEL: galleries (Galeri & Art Space)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.galleries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(100) NOT NULL UNIQUE,
    name VARCHAR(255) NOT NULL,
    alt_name VARCHAR(255) DEFAULT NULL,
    address TEXT NOT NULL,
    category VARCHAR(100) NOT NULL,
    status VARCHAR(50) NOT NULL DEFAULT 'Aktif',
    founder_or_owner VARCHAR(255) DEFAULT 'Belum ditemukan',
    established_year VARCHAR(50) DEFAULT 'Belum ditemukan',
    history TEXT DEFAULT NULL,
    focus TEXT DEFAULT NULL,
    events TEXT DEFAULT NULL,
    latitude DOUBLE PRECISION DEFAULT NULL,
    longitude DOUBLE PRECISION DEFAULT NULL,
    is_verified_coord BOOLEAN DEFAULT TRUE,
    website VARCHAR(255) DEFAULT 'Belum ditemukan',
    instagram VARCHAR(255) DEFAULT 'Belum ditemukan',
    image TEXT DEFAULT NULL,
    sources TEXT DEFAULT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 7. TABEL: feedbacks (Kritik & Saran Pengunjung)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.feedbacks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nama VARCHAR(150) DEFAULT NULL,
    email VARCHAR(150) DEFAULT NULL,
    jenis_masukan VARCHAR(50) NOT NULL DEFAULT 'Saran',
    isi TEXT NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'Belum dibaca',
    created_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 8. TABEL: artist_profiles (Profil Kustom & Foto Seniman)
-- ---------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.artist_profiles (
    id VARCHAR(100) PRIMARY KEY,
    name VARCHAR(255) DEFAULT NULL,
    role VARCHAR(255) DEFAULT NULL,
    era VARCHAR(100) DEFAULT NULL,
    category VARCHAR(50) DEFAULT NULL,
    avatar TEXT DEFAULT NULL,
    bio TEXT DEFAULT NULL,
    location VARCHAR(150) DEFAULT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- ---------------------------------------------------------------------
-- 9. ROW LEVEL SECURITY (RLS) POLICIES
-- Buka akses anon (public read & write sesuai kebutuhan aplikasi frontend)
-- ---------------------------------------------------------------------
ALTER TABLE public.albums ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.photos ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.events ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.galleries ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.feedbacks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.artist_profiles ENABLE ROW LEVEL SECURITY;

-- Policy Albums
CREATE POLICY "Public Read Albums" ON public.albums FOR SELECT USING (true);
CREATE POLICY "Anon Insert Albums" ON public.albums FOR INSERT WITH CHECK (true);
CREATE POLICY "Anon Update Albums" ON public.albums FOR UPDATE USING (true);
CREATE POLICY "Anon Delete Albums" ON public.albums FOR DELETE USING (true);

-- Policy Photos
CREATE POLICY "Public Read Photos" ON public.photos FOR SELECT USING (true);
CREATE POLICY "Anon Insert Photos" ON public.photos FOR INSERT WITH CHECK (true);
CREATE POLICY "Anon Update Photos" ON public.photos FOR UPDATE USING (true);
CREATE POLICY "Anon Delete Photos" ON public.photos FOR DELETE USING (true);

-- Policy Events
CREATE POLICY "Public Read Events" ON public.events FOR SELECT USING (true);
CREATE POLICY "Anon Insert Events" ON public.events FOR INSERT WITH CHECK (true);
CREATE POLICY "Anon Update Events" ON public.events FOR UPDATE USING (true);
CREATE POLICY "Anon Delete Events" ON public.events FOR DELETE USING (true);

-- Policy Bookings
CREATE POLICY "Public Read Bookings" ON public.bookings FOR SELECT USING (true);
CREATE POLICY "Anon Insert Bookings" ON public.bookings FOR INSERT WITH CHECK (true);
CREATE POLICY "Anon Update Bookings" ON public.bookings FOR UPDATE USING (true);
CREATE POLICY "Anon Delete Bookings" ON public.bookings FOR DELETE USING (true);

-- Policy Galleries
CREATE POLICY "Public Read Galleries" ON public.galleries FOR SELECT USING (true);
CREATE POLICY "Anon Insert Galleries" ON public.galleries FOR INSERT WITH CHECK (true);
CREATE POLICY "Anon Update Galleries" ON public.galleries FOR UPDATE USING (true);
CREATE POLICY "Anon Delete Galleries" ON public.galleries FOR DELETE USING (true);

-- Policy Feedbacks
CREATE POLICY "Public Read Feedbacks" ON public.feedbacks FOR SELECT USING (true);
CREATE POLICY "Anon Insert Feedbacks" ON public.feedbacks FOR INSERT WITH CHECK (true);
CREATE POLICY "Anon Update Feedbacks" ON public.feedbacks FOR UPDATE USING (true);
CREATE POLICY "Anon Delete Feedbacks" ON public.feedbacks FOR DELETE USING (true);

-- Policy Artist Profiles
CREATE POLICY "Public Read Artist Profiles" ON public.artist_profiles FOR SELECT USING (true);
CREATE POLICY "Anon Insert Artist Profiles" ON public.artist_profiles FOR INSERT WITH CHECK (true);
CREATE POLICY "Anon Update Artist Profiles" ON public.artist_profiles FOR UPDATE USING (true);
CREATE POLICY "Anon Delete Artist Profiles" ON public.artist_profiles FOR DELETE USING (true);

-- ---------------------------------------------------------------------
-- 10. SUPABASE STORAGE BUCKET SETUP
-- Buat bucket publik 'jejak-waktu-assets' untuk menyimpan foto unggahan
-- ---------------------------------------------------------------------
INSERT INTO storage.buckets (id, name, public)
VALUES ('jejak-waktu-assets', 'jejak-waktu-assets', true)
ON CONFLICT (id) DO NOTHING;

CREATE POLICY "Public Read Storage" ON storage.objects
FOR SELECT USING (bucket_id = 'jejak-waktu-assets');

CREATE POLICY "Anon Upload Storage" ON storage.objects
FOR INSERT WITH CHECK (bucket_id = 'jejak-waktu-assets');

CREATE POLICY "Anon Delete Storage" ON storage.objects
FOR DELETE USING (bucket_id = 'jejak-waktu-assets');
